spring.application.name=ecommerce
spring.datasource.url=${dbURL}
spring.datasource.username=${DbUser}
spring.datasource.password=${dbPassword}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true